use_gpu: True
state: 'INFO'
reproducibility: True
data_path: './data/'
eval_step: 1
metrics: ['Recall', 'NDCG']
topk: [10, 20, 50]
valid_metric: 'Recall@20'
eval_args: {
  group_by: 'user',
  order: 'TO',
  mode: 'full',
}
USER_ID_FIELD: 'uid'
ITEM_ID_FIELD: 'iid'
TIME_FIELD: 'timestamp'
load_col: {
  inter: ['uid', 'iid']
}
benchmark_filename: ['part1', 'part2', 'part3']
neg_sampling: {
  'uniform': 1
}
epochs: 300
stopping_step: 15
train_batch_size: 512